### ISSUE TITLE
Where is black and other colors?

### ISSUE THREAD

**Issue by csr** [hendriku/ColorPicker#8]
Hey, thanks for building this!

I don't think this is an issue with this library. I'm trying to figure out if this ring has all the colors? I can't figure out for example where black is. Is there any way to change the color brightness of the ring?

Thanks!

**Comment by hendriku** [comment]
Hi @csr ! Glad to hear you are interested in my color picker wheel. Regarding your issue: The color picker currently only supports "pure" colors. That means the wheel will vary the **hue** of the a color and keep the _brightness_ and _saturation_ at a constant level. Sad to say that using only a ring will make other variations impossible. I would recommend you to use additional color picker components e.g. a slider for brightness and saturation if you need them.

There is a fork of this repo which offers exactly such sliders: https://github.com/benjiburgess/ColorPicker

Also check out the HSB color model if you are curious about colors: https://medium.com/innovaccer-tech/rgb-vs-hsb-vs-hsl-demystified-1992d7273d3a
